sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lxt19981025

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBRc1T9xaJ3yfSF3BqW
    access-key-secret: C7BUOjcE9wRtqM0onqjDBFw7xEqjvi
    bucket-name: bobo-sky-itcast
